spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/rest-course
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


#??????????? ?????? ??? ???? ???????
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
#?????? ???? ?????????? ?? ????????? ????????????
spring.mail.properties.mail.smtp.startls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

server.port=8080
